nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: API - Projet 7 - Développeur d'application PHP/Symfony - OpenClassrooms
            version: 1.1.0

        securityDefinitions:
          bearerAuth:            # arbitrary name for the security scheme
            type: apiKey
            name: "Authorization"
            description: Add "Bearer" in front of the token
            in: header
    # 2) Apply the security globally to all operations
        security:
          - bearerAuth: []


        paths:
          /login:
            post:
              tags:
                - Utilisateur
              description: Authentification.
              produces:
                - application/json
              parameters:
                - name: user
                  description: Adresse email
                  in: body
                  required: true
                  schema:
                    type: object
                    properties:
                      username:
                        type: string
                      password:
                        type: string
              responses:
                '200':
                  description: Authentification réussie
                  schema:
                    type: object
                    properties:
                      token:
                        type: string
                '401':
                  description: Identifiants incorrects
                  schema:
                    type: object
                    properties:
                      error:
                        type: string

    areas: # to filter documented areas
        default:
            path_patterns:
                - /product
                - /user
                - /client
                #- ^/(?!/docs$) # Accepts routes under /api except /api/doc

