nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: API - Projet 7 - Développeur d'application PHP/Symfony - OpenClassrooms
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns:
                - /product
                - /user
                - /client
                #- ^/(?!/docs$) # Accepts routes under /api except /api/doc

